services:
  frontend:
    image: ghcr.io/blockscout/frontend:${FRONTEND_DOCKER_TAG:-latest}
    pull_policy: always
    platform: linux/amd64
    restart: unless-stopped
    expose:
      - "3000"
    environment:
      HOSTNAME: 0.0.0.0
      PORT: 3000
      NEXT_PUBLIC_USE_NEXT_JS_PROXY: "false"
      NEXT_PUBLIC_API_PROTOCOL: https
      NEXT_PUBLIC_API_HOST: explorer-frontend-y3vx1v-aaa30a-72-60-35-83.sslip.io
      NEXT_PUBLIC_API_BASE_PATH: /
      NEXT_PUBLIC_API_WEBSOCKET_PROTOCOL: wss
      NEXT_PUBLIC_STATS_API_HOST: ""
      NEXT_PUBLIC_STATS_API_BASE_PATH: /
      NEXT_PUBLIC_VISUALIZE_API_HOST: https://explorer-frontend-y3vx1v-aaa30a-72-60-35-83.sslip.io
      NEXT_PUBLIC_VISUALIZE_API_BASE_PATH: /
      NEXT_PUBLIC_NETWORK_NAME: ${NEXT_PUBLIC_NETWORK_NAME:-Reef Dev Cluster}
      NEXT_PUBLIC_NETWORK_SHORT_NAME: ${NEXT_PUBLIC_NETWORK_SHORT_NAME:-Reef}
      NEXT_PUBLIC_NETWORK_ID: ${NEXT_PUBLIC_NETWORK_ID:-13939}
      NEXT_PUBLIC_NETWORK_RPC_URL: ${NEXT_PUBLIC_NETWORK_RPC_URL:-http://eth.reef-node-reefdevcluster-808c46-72-60-35-83.sslip.io}
      NEXT_PUBLIC_NETWORK_CURRENCY_NAME: ${NEXT_PUBLIC_NETWORK_CURRENCY_NAME:-Reef}
      NEXT_PUBLIC_NETWORK_CURRENCY_SYMBOL: ${NEXT_PUBLIC_NETWORK_CURRENCY_SYMBOL:-REEF}
      NEXT_PUBLIC_NETWORK_CURRENCY_DECIMALS: ${NEXT_PUBLIC_NETWORK_CURRENCY_DECIMALS:-18}
      NEXT_PUBLIC_NETWORK_VERIFICATION_TYPE: ${NEXT_PUBLIC_NETWORK_VERIFICATION_TYPE:-validation}
      NEXT_PUBLIC_IS_TESTNET: ${NEXT_PUBLIC_IS_TESTNET:-true}
      NEXT_PUBLIC_APP_PROTOCOL: https
      NEXT_PUBLIC_APP_HOST: explorer-frontend-y3vx1v-aaa30a-72-60-35-83.sslip.io
      NEXT_PUBLIC_HOMEPAGE_CHARTS: "${NEXT_PUBLIC_HOMEPAGE_CHARTS:-['daily_txs']}"
      NEXT_PUBLIC_API_SPEC_URL: ${NEXT_PUBLIC_API_SPEC_URL:-https://raw.githubusercontent.com/blockscout/blockscout-api-v2-swagger/main/swagger.yaml}

  proxy:
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      - frontend
    expose:
      - "80"
    environment:
      BACK_PROXY_PASS: ${BACK_PROXY_PASS:-http://reef-explorer-ipwkoo-6aeed5-72-60-35-83.sslip.io}
    volumes:
      - ./reef-hosted-frontend.proxy.conf.template:/etc/nginx/templates/default.conf.template:ro
